name: 'Genshin-Profile-Exporter'
description: 'Exports the information of the specified users Genshin data, provided through EnkaNetwork & Akasha Systems'
author: 'QuantumPie'

inputs:
    uuid:
        description: 'UUID of the Genshin account'
        required: true
    usage:
        description: 'Intended end-user use-case of this Action'
        required: true
    goodSrc:
        description: 'Optional location of account GOOD data. Defaults to EnkaNetwork if undefined'
        required: false

outputs:
    json:
        description: 'Obtained information of the provided UUID'

runs:
    using: node16
    main: dist/index.js
